name: 摸鱼办

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '30 2 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: 开始
      env:
        SEND_KEY: ${{ secrets.SEND_KEY }}
        TZ: Asia/Shanghai
      run: |
        pip install requests
        pip install datetime
        python moyu.py

